import { createHmac } from "node:crypto";
import { describe, expect, test } from "bun:test";
import {
  SuperchatError,
  SuperchatSignatureError,
} from "../src/errors";
import { computeSignature, constructWebhookEvent, verifyWebhookSignature } from "../src/signature";
import { TEST_SECRET, signPayload } from "./fixtures";

const PAYLOAD = JSON.stringify({
  id: "evt_2ac1",
  event: "payment.completed",
  created_at: "2026-09-20T10:00:00.000Z",
  data: { id: "pay_1", amount: 750 },
});

function nowSeconds(): number {
  return Math.floor(Date.now() / 1000);
}

describe("computeSignature", () => {
  test("matches the platform algorithm (HMAC-SHA256 of `<timestamp>.<payload>`)", () => {
    const timestamp = 1_760_000_000;
    const expected = createHmac("sha256", TEST_SECRET).update(`${timestamp}.${PAYLOAD}`).digest("hex");

    expect(computeSignature(PAYLOAD, TEST_SECRET, timestamp)).toBe(expected);
  });
});

describe("verifyWebhookSignature", () => {
  test("accepts a signature generated by the platform", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET);

    expect(verifyWebhookSignature({ payload: PAYLOAD, signatureHeader: header, secret: TEST_SECRET })).toBe(true);
  });

  test("accepts Buffer and Uint8Array payloads", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET);
    const bytes = new TextEncoder().encode(PAYLOAD);

    expect(
      verifyWebhookSignature({ payload: Buffer.from(PAYLOAD), signatureHeader: header, secret: TEST_SECRET }),
    ).toBe(true);
    expect(verifyWebhookSignature({ payload: bytes, signatureHeader: header, secret: TEST_SECRET })).toBe(true);
  });

  test("accepts an uppercase hex signature", () => {
    const [timestampPart, hashPart] = signPayload(PAYLOAD, TEST_SECRET).split(",");
    const header = `${timestampPart},v1=${(hashPart ?? "").slice("v1=".length).toUpperCase()}`;

    expect(verifyWebhookSignature({ payload: PAYLOAD, signatureHeader: header, secret: TEST_SECRET })).toBe(true);
  });

  test("rejects a wrong secret", () => {
    const header = signPayload(PAYLOAD, "whsec_other_secret");

    expect(verifyWebhookSignature({ payload: PAYLOAD, signatureHeader: header, secret: TEST_SECRET })).toBe(false);
  });

  test("rejects a tampered payload", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET);

    expect(
      verifyWebhookSignature({
        payload: PAYLOAD.replace("750", "750000"),
        signatureHeader: header,
        secret: TEST_SECRET,
      }),
    ).toBe(false);
  });

  test("rejects a signature of a different length", () => {
    const header = `t=${nowSeconds()},v1=abcd`;

    expect(verifyWebhookSignature({ payload: PAYLOAD, signatureHeader: header, secret: TEST_SECRET })).toBe(false);
  });

  test("rejects a non-hex signature", () => {
    const valid = signPayload(PAYLOAD, TEST_SECRET).split("v1=")[1] ?? "";
    const header = `t=${nowSeconds()},v1=${"z".repeat(valid.length)}`;

    expect(verifyWebhookSignature({ payload: PAYLOAD, signatureHeader: header, secret: TEST_SECRET })).toBe(false);
  });

  test("rejects an expired timestamp with the default tolerance", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET, nowSeconds() - 3_600);

    expect(verifyWebhookSignature({ payload: PAYLOAD, signatureHeader: header, secret: TEST_SECRET })).toBe(false);
  });

  test("honours a custom tolerance", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET, nowSeconds() - 3_600);

    expect(
      verifyWebhookSignature({
        payload: PAYLOAD,
        signatureHeader: header,
        secret: TEST_SECRET,
        toleranceInSeconds: 7_200,
      }),
    ).toBe(true);
  });

  test("disables the replay check when tolerance is 0", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET, nowSeconds() - 86_400);

    expect(
      verifyWebhookSignature({
        payload: PAYLOAD,
        signatureHeader: header,
        secret: TEST_SECRET,
        toleranceInSeconds: 0,
      }),
    ).toBe(true);
  });

  test("rejects a future timestamp outside the tolerance", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET, nowSeconds() + 3_600);

    expect(verifyWebhookSignature({ payload: PAYLOAD, signatureHeader: header, secret: TEST_SECRET })).toBe(false);
  });

  test("rejects missing and malformed headers", () => {
    const cases = ["", "garbage", "t=abc,v1=deadbeef", "v1=deadbeef", "t=1760000000", "t=,v1="];

    for (const signatureHeader of cases) {
      expect(verifyWebhookSignature({ payload: PAYLOAD, signatureHeader, secret: TEST_SECRET })).toBe(false);
    }
  });

  test("throws when the signing secret is missing", () => {
    expect(() => verifyWebhookSignature({ payload: PAYLOAD, signatureHeader: "t=1,v1=ab", secret: "" })).toThrow(
      SuperchatSignatureError,
    );
  });
});

describe("constructWebhookEvent", () => {
  test("returns the parsed envelope of a valid request", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET);

    const event = constructWebhookEvent<{ id: string }>({
      payload: PAYLOAD,
      signatureHeader: header,
      secret: TEST_SECRET,
    });

    expect(event.id).toBe("evt_2ac1");
    expect(event.event).toBe("payment.completed");
    expect(event.created_at).toBe("2026-09-20T10:00:00.000Z");
    expect(event.data.id).toBe("pay_1");
  });

  test("throws signature_mismatch for a tampered payload", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET);

    try {
      constructWebhookEvent({ payload: `${PAYLOAD} `, signatureHeader: header, secret: TEST_SECRET });
      throw new Error("expected constructWebhookEvent to throw");
    } catch (error) {
      expect(error).toBeInstanceOf(SuperchatSignatureError);
      expect((error as SuperchatSignatureError).code).toBe("signature_mismatch");
    }
  });

  test("throws timestamp_outside_tolerance for a stale request", () => {
    const header = signPayload(PAYLOAD, TEST_SECRET, nowSeconds() - 3_600);

    try {
      constructWebhookEvent({ payload: PAYLOAD, signatureHeader: header, secret: TEST_SECRET });
      throw new Error("expected constructWebhookEvent to throw");
    } catch (error) {
      expect((error as SuperchatSignatureError).code).toBe("timestamp_outside_tolerance");
    }
  });

  test("throws malformed_header when the header is unusable", () => {
    try {
      constructWebhookEvent({ payload: PAYLOAD, signatureHeader: "nope", secret: TEST_SECRET });
      throw new Error("expected constructWebhookEvent to throw");
    } catch (error) {
      expect((error as SuperchatSignatureError).code).toBe("malformed_header");
    }
  });

  test("throws invalid_payload for a verified but non-JSON body", () => {
    const body = "not json";
    const header = signPayload(body, TEST_SECRET);

    try {
      constructWebhookEvent({ payload: body, signatureHeader: header, secret: TEST_SECRET });
      throw new Error("expected constructWebhookEvent to throw");
    } catch (error) {
      expect(error).toBeInstanceOf(SuperchatError);
      expect((error as SuperchatError).code).toBe("invalid_payload");
    }
  });

  test("throws invalid_payload when the envelope has no event field", () => {
    const body = JSON.stringify({ id: "evt_1", data: {} });
    const header = signPayload(body, TEST_SECRET);

    try {
      constructWebhookEvent({ payload: body, signatureHeader: header, secret: TEST_SECRET });
      throw new Error("expected constructWebhookEvent to throw");
    } catch (error) {
      expect((error as SuperchatError).code).toBe("invalid_payload");
    }
  });
});
